version: '3.4'

services:
  poort8.ishare.common:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ClientId=EU.EORI.NL888888881
      - Certificate=
      - CertificatePassword=
      - CertificateChain=
      - CertificateChainPassword=
      - SchemeOwnerUrl=https://scheme.isharetest.net
      - SchemeOwnerIdentifier=EU.EORI.NL000000000
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro